// src/components/Footer.tsx
const Footer = () => {
  return (
    <footer className="bg-gradient-card/50 border-t border-border/20">
      <div className="container mx-auto px-4 py-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Quick Links */}
          <div>
            <h4 className="font-semibold text-foreground mb-3 text-sm">Explore</h4>
            <ul className="space-y-2 text-muted-foreground text-xs">
              <li><a href="#" className="hover:text-primary transition-colors">Browse Videos</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Mental Health</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Mindfulness</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Personal Growth</a></li>
            </ul>
          </div>

          {/* Support */}
          <div>
            <h4 className="font-semibold text-foreground mb-3 text-sm">Support</h4>
            <ul className="space-y-2 text-muted-foreground text-xs">
              <li><a href="#" className="hover:text-primary transition-colors">Help Center</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Crisis Resources</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Privacy Policy</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Terms of Service</a></li>
            </ul>
          </div>

          {/* Emergency Support */}
          <div>
            <h4 className="font-semibold text-foreground mb-3 text-sm">Emergency Support</h4>
            <div className="space-y-2 text-xs">
              <p className="text-red-500">Crisis Text Line: 741741</p>
              <p className="text-red-500">Suicide Prevention: 988</p>
            </div>
          </div>
        </div>

        <div className="border-t border-border/20 mt-4 pt-3 text-center">
          <p className="text-muted-foreground text-xs">
            © 2024 Better & Bliss. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/layout/Footer.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'

const currentYear = new Date().getFullYear()

const footerLinks = {
  product: [
    { name: 'Browse', href: '/browse' },
    { name: 'Audio', href: '/audio' },
    { name: 'Meditate', href: '/meditate' },
    { name: 'Experts', href: '/experts' }
  ],
  company: [
    { name: 'About', href: '/about' },
    { name: 'Blog', href: '/read' },
    { name: 'Support', href: '/support' }
  ],
  legal: [
    { name: 'Privacy Policy', href: '/privacy-policy' },
    { name: 'Terms of Service', href: '/terms' }
  ]
}
</script>

<template>
  <footer class="bg-gray-900 text-gray-300">
    <div class="container mx-auto px-4 py-12">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <!-- Brand -->
        <div class="col-span-1">
          <RouterLink to="/" class="text-xl font-bold text-white">
            Soul Shapers
          </RouterLink>
          <p class="mt-4 text-sm text-gray-400">
            Transform your mind, body, and soul with expert-led coaching and mindfulness practices.
          </p>
        </div>

        <!-- Product Links -->
        <div>
          <h3 class="text-sm font-semibold text-white uppercase tracking-wider mb-4">
            Product
          </h3>
          <ul class="space-y-2">
            <li v-for="link in footerLinks.product" :key="link.name">
              <RouterLink
                :to="link.href"
                class="text-sm hover:text-white transition-colors"
              >
                {{ link.name }}
              </RouterLink>
            </li>
          </ul>
        </div>

        <!-- Company Links -->
        <div>
          <h3 class="text-sm font-semibold text-white uppercase tracking-wider mb-4">
            Company
          </h3>
          <ul class="space-y-2">
            <li v-for="link in footerLinks.company" :key="link.name">
              <RouterLink
                :to="link.href"
                class="text-sm hover:text-white transition-colors"
              >
                {{ link.name }}
              </RouterLink>
            </li>
          </ul>
        </div>

        <!-- Legal Links -->
        <div>
          <h3 class="text-sm font-semibold text-white uppercase tracking-wider mb-4">
            Legal
          </h3>
          <ul class="space-y-2">
            <li v-for="link in footerLinks.legal" :key="link.name">
              <RouterLink
                :to="link.href"
                class="text-sm hover:text-white transition-colors"
              >
                {{ link.name }}
              </RouterLink>
            </li>
          </ul>
        </div>
      </div>

      <!-- Bottom Bar -->
      <div class="mt-12 pt-8 border-t border-gray-800">
        <p class="text-sm text-gray-400 text-center">
          &copy; {{ currentYear }} Soul Shapers Studio. All rights reserved.
        </p>
      </div>
    </div>
  </footer>
</template>
