// src/pages/AudioBrowsePage.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { contentService } from '@/services/content.service'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { 
  Search, 
  Bell, 
  User, 
  Play, 
  Clock,
  Headphones,
  ChevronLeft,
  ChevronRight,
  ArrowLeft
} from 'lucide-vue-next'

const router = useRouter()
const authStore = useAuthStore()

const audioContent = ref<any[]>([])
const categories = ref<any[]>([])
const loading = ref(true)
const error = ref('')
const searchQuery = ref('')

const user = computed(() => authStore.user)

const filteredContent = computed(() => {
  if (!searchQuery.value) return audioContent.value
  const query = searchQuery.value.toLowerCase()
  return audioContent.value.filter(item =>
    item.title?.toLowerCase().includes(query) ||
    item.expert_name?.toLowerCase().includes(query)
  )
})

const formatDuration = (seconds: number) => {
  if (!seconds) return ''
  const mins = Math.floor(seconds / 60)
  return `${mins}m`
}

const fetchAudioContent = async () => {
  loading.value = true
  error.value = ''
  
  try {
    const content = await contentService.getAudioContent(undefined, 50)
    audioContent.value = content || []
    
    // Group by category
    const catResponse = await contentService.getCategories()
    categories.value = catResponse.categories || []
  } catch (err: any) {
    error.value = err.message || 'Failed to load audio content'
  } finally {
    loading.value = false
  }
}

const handleLogout = async () => {
  await authStore.logout()
  router.push('/')
}

onMounted(() => {
  fetchAudioContent()
})
</script>

<template>
  <div class="min-h-screen bg-[#0a0a0a] text-white">
    <!-- Top Navigation -->
    <header class="fixed top-0 left-0 right-0 z-50 bg-gradient-to-b from-black to-transparent">
      <div class="flex items-center justify-between px-6 py-4">
        <!-- Left: Back & Logo -->
        <div class="flex items-center gap-6">
          <button @click="router.back()" class="p-2 text-gray-400 hover:text-white">
            <ArrowLeft class="h-5 w-5" />
          </button>
          <RouterLink to="/" class="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">
            Soul Shapers
          </RouterLink>
        </div>
        
        <!-- Center: Nav -->
        <nav class="hidden md:flex items-center gap-6">
          <RouterLink to="/browse" class="text-sm text-gray-300 hover:text-white">Home</RouterLink>
          <RouterLink to="/audio" class="text-sm font-medium text-white">Audio</RouterLink>
          <RouterLink to="/meditate" class="text-sm text-gray-300 hover:text-white">Meditate</RouterLink>
          <RouterLink to="/experts" class="text-sm text-gray-300 hover:text-white">Experts</RouterLink>
        </nav>
        
        <!-- Right: Actions -->
        <div class="flex items-center gap-4">
          <div class="relative group">
            <button class="flex items-center gap-2">
              <div class="w-8 h-8 rounded bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
                <User class="h-4 w-4" />
              </div>
            </button>
          </div>
        </div>
      </div>
    </header>
    
    <main class="pt-20 px-6 md:px-12 pb-16">
      <!-- Page Header -->
      <div class="mb-8">
        <h1 class="text-3xl md:text-4xl font-bold mb-2">Audio Library</h1>
        <p class="text-gray-400">Guided meditations and audio coaching</p>
      </div>
      
      <!-- Search -->
      <div class="relative max-w-md mb-8">
        <Search class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-500" />
        <Input
          v-model="searchQuery"
          type="search"
          placeholder="Search audio..."
          class="pl-12 bg-gray-900/50 border-gray-800 text-white placeholder:text-gray-500"
        />
      </div>
      
      <!-- Loading -->
      <div v-if="loading" class="flex justify-center py-20">
        <div class="w-12 h-12 border-4 border-purple-500 border-t-transparent rounded-full animate-spin" />
      </div>
      
      <!-- Error -->
      <div v-else-if="error" class="text-center py-20">
        <p class="text-red-400 mb-4">{{ error }}</p>
        <Button @click="fetchAudioContent">Try Again</Button>
      </div>
      
      <!-- Content Grid -->
      <div v-else class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
        <RouterLink
          v-for="item in filteredContent"
          :key="item.id"
          :to="`/audio/${item.id}`"
          class="group"
        >
          <!-- Card -->
          <div class="relative aspect-square rounded-xl overflow-hidden bg-gray-800 mb-3">
            <img
              v-if="item.thumbnail_url"
              :src="item.thumbnail_url"
              :alt="item.title"
              class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
            />
            <div v-else class="w-full h-full bg-gradient-to-br from-purple-600 to-pink-600 flex items-center justify-center">
              <Headphones class="h-16 w-16 text-white/50" />
            </div>
            
            <!-- Play Overlay -->
            <div class="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
              <div class="w-14 h-14 rounded-full bg-white flex items-center justify-center shadow-lg">
                <Play class="h-7 w-7 text-black ml-0.5" />
              </div>
            </div>
            
            <!-- Duration Badge -->
            <div v-if="item.duration_seconds" class="absolute bottom-3 right-3 px-2 py-1 bg-black/80 rounded-full text-xs flex items-center gap-1">
              <Clock class="h-3 w-3" />
              {{ formatDuration(item.duration_seconds) }}
            </div>
            
            <!-- Premium Badge -->
            <div v-if="item.access_tier === 'premium'" class="absolute top-3 right-3 px-2 py-1 bg-yellow-500 rounded text-xs text-black font-medium">
              Premium
            </div>
          </div>
          
          <!-- Info -->
          <h3 class="font-semibold text-white line-clamp-1 group-hover:text-purple-400 transition-colors">
            {{ item.title }}
          </h3>
          <p class="text-sm text-gray-400 line-clamp-1">
            {{ item.expert_name }}
          </p>
        </RouterLink>
      </div>
      
      <!-- Empty State -->
      <div v-if="!loading && !error && filteredContent.length === 0" class="text-center py-20">
        <Headphones class="h-16 w-16 text-gray-600 mx-auto mb-4" />
        <p class="text-gray-400 text-lg">No audio content found</p>
        <p class="text-gray-500 text-sm mt-2">Try adjusting your search or check back later</p>
      </div>
    </main>
  </div>
</template>

// src/pages/AudioBrowsePage.tsx
// src/pages/AudioBrowsePage.tsx - Browse Real Audio Content with UUIDs
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Button } from '@/components/ui/button';
import { contentService } from '@/services/content.service';
import { Play, Clock, User, Loader2, AlertCircle, RefreshCw } from 'lucide-react';

interface AudioContentItem {
  id: string; // UUID
  title: string;
  description: string;
  expert_name: string;
  expert_title: string;
  duration_seconds: number;
  category_name: string;
  thumbnail_url?: string;
  access_tier: 'free' | 'premium';
}

const AudioBrowsePage = () => {
  const navigate = useNavigate();
  const [audioContent, setAudioContent] = useState<AudioContentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadAudioContent = async () => {
    try {
      setLoading(true);
      setError(null);
      console.log('🎵 Loading audio content from backend...');

      const content = await contentService.getAudioContent();

      if (content.length === 0) {
        setError('No audio content found in database. Please add audio content with UUIDs.');
      } else {
        setAudioContent(content as any);
        console.log(`✅ Loaded ${content.length} audio items`);
      }
    } catch (err: any) {
      console.error('❌ Failed to load audio content:', err);
      setError(err.message || 'Failed to load audio content from backend');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAudioContent();
  }, []);

  const formatDuration = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const handlePlayAudio = (audioId: string, accessTier: string) => {
    if (accessTier === 'premium') {
      // You might want to check user subscription here
      console.log('Premium content clicked');
    }
    navigate(`/audio/${audioId}`);
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <div className="container mx-auto px-6 py-12">
        {/* Header Section */}
        <div className="mb-12">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
            Audio Library
          </h1>
          <p className="text-gray-600 dark:text-gray-400 text-lg">
            Browse and listen to audio content from our collection
          </p>
        </div>

        {/* Loading State */}
        {loading && (
          <div className="flex flex-col items-center justify-center py-20">
            <Loader2 className="w-12 h-12 text-purple-600 animate-spin mb-4" />
            <p className="text-gray-600 dark:text-gray-400">Loading audio content...</p>
          </div>
        )}

        {/* Error State */}
        {error && !loading && (
          <div className="max-w-2xl mx-auto">
            <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-6">
              <div className="flex items-start gap-4 mb-4">
                <AlertCircle className="w-6 h-6 text-red-600 dark:text-red-400 flex-shrink-0 mt-1" />
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-red-900 dark:text-red-100 mb-2">
                    Unable to Load Audio Content
                  </h3>
                  <p className="text-red-800 dark:text-red-200 mb-4">{error}</p>
                </div>
              </div>

              <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mb-4">
                <p className="text-sm text-blue-900 dark:text-blue-100 font-semibold mb-2">
                  To add audio content:
                </p>
                <ol className="text-sm text-blue-800 dark:text-blue-200 space-y-1 ml-4">
                  <li>1. Ensure your backend is running</li>
                  <li>2. Add content to the database with UUIDs</li>
                  <li>3. Set content_type = 'audio'</li>
                  <li>4. Refresh this page</li>
                </ol>
              </div>

              <div className="flex gap-3">
                <Button
                  onClick={loadAudioContent}
                  variant="default"
                  className="bg-purple-600 hover:bg-purple-700"
                >
                  <RefreshCw className="w-4 h-4 mr-2" />
                  Retry
                </Button>
                <Button
                  onClick={() => navigate('/')}
                  variant="outline"
                >
                  Back to Home
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Content Grid */}
        {!loading && !error && audioContent.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {audioContent.map((audio) => (
              <div
                key={audio.id}
                onClick={() => handlePlayAudio(audio.id, audio.access_tier)}
                className="bg-white dark:bg-gray-800 rounded-lg shadow-md hover:shadow-xl transition-all duration-300 cursor-pointer group overflow-hidden border border-gray-200 dark:border-gray-700"
              >
                {/* Thumbnail */}
                <div className="relative aspect-video w-full bg-gradient-to-br from-purple-500 to-indigo-600 overflow-hidden">
                  {audio.thumbnail_url ? (
                    <img
                      src={audio.thumbnail_url}
                      alt={audio.title}
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center">
                      <Play className="w-12 h-12 text-white opacity-50" />
                    </div>
                  )}

                  {/* Play Button Overlay */}
                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                    <div className="w-14 h-14 rounded-full bg-purple-600 flex items-center justify-center">
                      <Play className="w-6 h-6 text-white fill-current ml-1" />
                    </div>
                  </div>

                  {/* Access Tier Badge */}
                  {audio.access_tier === 'premium' && (
                    <div className="absolute top-2 right-2 bg-amber-500 text-white text-xs font-bold px-2 py-1 rounded">
                      PREMIUM
                    </div>
                  )}
                </div>

                {/* Content */}
                <div className="p-4">
                  <h3 className="font-semibold text-gray-900 dark:text-white mb-2 line-clamp-2 group-hover:text-purple-600 dark:group-hover:text-purple-400 transition-colors">
                    {audio.title}
                  </h3>

                  <p className="text-sm text-gray-600 dark:text-gray-400 mb-3 line-clamp-2">
                    {audio.description}
                  </p>

                  {/* Metadata */}
                  <div className="flex items-center gap-4 text-xs text-gray-500 dark:text-gray-400">
                    <div className="flex items-center gap-1">
                      <User className="w-3 h-3" />
                      <span className="truncate">{audio.expert_name}</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      <span>{formatDuration(audio.duration_seconds)}</span>
                    </div>
                  </div>

                  {/* Category */}
                  {audio.category_name && (
                    <div className="mt-3">
                      <span className="inline-block bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-300 text-xs font-medium px-2 py-1 rounded">
                        {audio.category_name}
                      </span>
                    </div>
                  )}

                  {/* UUID Display (for debugging) */}
                  <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-700">
                    <p className="text-xs text-gray-400 dark:text-gray-600 font-mono truncate" title={audio.id}>
                      ID: {audio.id.substring(0, 8)}...
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Info Box */}
        {!loading && !error && audioContent.length > 0 && (
          <div className="mt-12 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-6">
            <h3 className="text-lg font-semibold text-blue-900 dark:text-blue-100 mb-3">
              ℹ️ How Audio Streaming Works
            </h3>
            <ul className="space-y-2 text-sm text-blue-800 dark:text-blue-200">
              <li>• Content is fetched from your backend database with UUIDs</li>
              <li>• Click any audio card to start streaming</li>
              <li>• Streaming uses HLS format via: <code className="bg-blue-100 dark:bg-blue-900/40 px-2 py-0.5 rounded font-mono text-xs">/api/streaming/content/{'{UUID}'}/stream</code></li>
              <li>• Premium content may require authentication</li>
            </ul>
          </div>
        )}
      </div>

      <Footer />
    </div>
  );
};

export default AudioBrowsePage;
