// src/pages/ExpertsPage.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { Input } from '@/components/ui/input'
import { 
  ArrowLeft,
  User,
  Search,
  Play,
  Star,
  Video
} from 'lucide-vue-next'

interface Expert {
  id: string
  name: string
  title: string
  photo_url?: string
  specialty: string
  video_count?: number
}

const router = useRouter()
const authStore = useAuthStore()

const experts = ref<Expert[]>([])
const loading = ref(true)
const searchQuery = ref('')

const user = computed(() => authStore.user)

const filteredExperts = computed(() => {
  if (!searchQuery.value) return experts.value
  const query = searchQuery.value.toLowerCase()
  return experts.value.filter(e => 
    e.name.toLowerCase().includes(query) ||
    e.specialty?.toLowerCase().includes(query)
  )
})

const fetchExperts = async () => {
  loading.value = true
  
  // Simulated experts data - in production this would come from an API
  experts.value = [
    { id: '1', name: 'Dr. Sarah Chen', title: 'Mindfulness Expert', photo_url: '', specialty: 'Meditation', video_count: 45 },
    { id: '2', name: 'Michael Torres', title: 'Life Coach', photo_url: '', specialty: 'Personal Growth', video_count: 32 },
    { id: '3', name: 'Emma Wilson', title: 'Wellness Coach', photo_url: '', specialty: 'Wellness', video_count: 28 },
    { id: '4', name: 'Dr. James Park', title: 'Neuroscientist', photo_url: '', specialty: 'Mind Training', video_count: 24 },
    { id: '5', name: 'Lisa Roberts', title: 'Yoga Instructor', photo_url: '', specialty: 'Yoga & Movement', video_count: 56 },
    { id: '6', name: 'David Martinez', title: 'Breathwork Expert', photo_url: '', specialty: 'Breathwork', video_count: 18 }
  ]
  
  loading.value = false
}

onMounted(() => {
  fetchExperts()
})
</script>

<template>
  <div class="min-h-screen bg-[#0a0a0a] text-white">
    <!-- Top Navigation -->
    <header class="fixed top-0 left-0 right-0 z-50 bg-gradient-to-b from-black to-transparent">
      <div class="flex items-center justify-between px-6 py-4">
        <div class="flex items-center gap-6">
          <button @click="router.back()" class="p-2 text-gray-400 hover:text-white">
            <ArrowLeft class="h-5 w-5" />
          </button>
          <RouterLink to="/" class="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">
            Soul Shapers
          </RouterLink>
        </div>
        
        <nav class="hidden md:flex items-center gap-6">
          <RouterLink to="/browse" class="text-sm text-gray-300 hover:text-white">Home</RouterLink>
          <RouterLink to="/audio" class="text-sm text-gray-300 hover:text-white">Audio</RouterLink>
          <RouterLink to="/meditate" class="text-sm text-gray-300 hover:text-white">Meditate</RouterLink>
          <RouterLink to="/experts" class="text-sm font-medium text-white">Experts</RouterLink>
        </nav>
        
        <div class="flex items-center gap-4">
          <div class="w-8 h-8 rounded bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
            <User class="h-4 w-4" />
          </div>
        </div>
      </div>
    </header>
    
    <main class="pt-20 px-6 md:px-12 pb-16">
      <!-- Page Header -->
      <div class="mb-8">
        <h1 class="text-3xl md:text-4xl font-bold mb-2">Our Experts</h1>
        <p class="text-gray-400">Learn from world-class teachers and coaches</p>
      </div>
      
      <!-- Search -->
      <div class="relative max-w-md mb-8">
        <Search class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-500" />
        <Input
          v-model="searchQuery"
          type="search"
          placeholder="Search experts..."
          class="pl-12 bg-gray-900/50 border-gray-800 text-white placeholder:text-gray-500"
        />
      </div>
      
      <!-- Loading -->
      <div v-if="loading" class="flex justify-center py-20">
        <div class="w-12 h-12 border-4 border-purple-500 border-t-transparent rounded-full animate-spin" />
      </div>
      
      <!-- Experts Grid -->
      <div v-else class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
        <RouterLink
          v-for="expert in filteredExperts"
          :key="expert.id"
          :to="`/experts/${expert.id}`"
          class="group text-center"
        >
          <!-- Avatar -->
          <div class="relative mx-auto w-32 h-32 md:w-40 md:h-40 rounded-full overflow-hidden bg-gradient-to-br from-purple-500 to-pink-500 mb-4 group-hover:scale-105 transition-transform">
            <img
              v-if="expert.photo_url"
              :src="expert.photo_url"
              :alt="expert.name"
              class="w-full h-full object-cover"
            />
            <div v-else class="w-full h-full flex items-center justify-center">
              <User class="h-16 w-16 text-white/50" />
            </div>
            
            <!-- Hover Overlay -->
            <div class="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
              <Play class="h-10 w-10 text-white" />
            </div>
          </div>
          
          <!-- Info -->
          <h3 class="font-semibold text-white group-hover:text-purple-400 transition-colors">
            {{ expert.name }}
          </h3>
          <p class="text-sm text-gray-400 mb-2">{{ expert.title }}</p>
          
          <!-- Stats -->
          <div class="flex items-center justify-center gap-3 text-xs text-gray-500">
            <span class="flex items-center gap-1 px-2 py-1 rounded-full bg-gray-800">
              {{ expert.specialty }}
            </span>
            <span v-if="expert.video_count" class="flex items-center gap-1">
              <Video class="h-3 w-3" />
              {{ expert.video_count }}
            </span>
          </div>
        </RouterLink>
      </div>
      
      <!-- Empty State -->
      <div v-if="!loading && filteredExperts.length === 0" class="text-center py-20">
        <User class="h-16 w-16 text-gray-600 mx-auto mb-4" />
        <p class="text-gray-400 text-lg">No experts found</p>
      </div>
    </main>
  </div>
</template>

// src/pages/ExpertsPage.tsx
// src/pages/ExpertsPage.tsx - Explore and discover our expert wellness professionals
import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import Header from '@/components/Header';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { getAllExperts, getExpertsBySpecialty } from '@/data/dummyExperts';
import { Expert } from '@/types/expert.types';
import {
  Brain,
  Sparkles,
  Heart,
  Activity,
  Shield,
  Lightbulb,
  Search,
  Star,
  Video,
  Clock,
  Award
} from 'lucide-react';

const SPECIALTY_ICONS = {
  'Clinical Psychologists': Brain,
  'Mindfulness Instructors': Sparkles,
  'Relationship Therapists': Heart,
  'Addiction Counselors': Activity,
  'Trauma Specialists': Shield,
  'Life Coaches': Lightbulb,
};

const ExpertsPage = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const specialtyParam = searchParams.get('specialty');

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedSpecialty, setSelectedSpecialty] = useState<string | null>(specialtyParam);
  const [experts, setExperts] = useState<Expert[]>([]);

  useEffect(() => {
    // Load experts based on selected specialty
    if (selectedSpecialty) {
      setExperts(getExpertsBySpecialty(selectedSpecialty));
    } else {
      setExperts(getAllExperts());
    }
  }, [selectedSpecialty]);

  // Filter experts by search query
  const filteredExperts = experts.filter(expert =>
    expert.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    expert.specialty.toLowerCase().includes(searchQuery.toLowerCase()) ||
    expert.expertise.some(exp => exp.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  const specialties = [
    'Clinical Psychologists',
    'Mindfulness Instructors',
    'Relationship Therapists',
    'Addiction Counselors',
    'Trauma Specialists',
    'Life Coaches'
  ];

  const handleExpertClick = (expertId: string) => {
    navigate(`/experts/${expertId}`);
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />

      {/* Hero Section */}
      <div className="bg-gradient-to-br from-primary/10 via-purple-50 to-background dark:from-primary/5 dark:via-background dark:to-background border-b">
        <div className="max-w-7xl mx-auto px-6 py-16">
          <div className="text-center max-w-3xl mx-auto">
            <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">
              Meet Our Expert Wellness Professionals
            </h1>
            <p className="text-lg text-muted-foreground mb-8">
              Connect with certified therapists, coaches, and mindfulness experts dedicated to your mental health and personal growth.
            </p>

            {/* Search Bar */}
            <div className="relative max-w-2xl mx-auto">
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-muted-foreground" />
              <Input
                placeholder="Search by name, specialty, or expertise..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-12 h-14 text-base rounded-full border-2 focus:border-primary"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Filter Section */}
      <div className="border-b bg-card">
        <div className="max-w-7xl mx-auto px-6 py-6">
          <div className="flex items-center gap-3 flex-wrap">
            <span className="text-sm font-semibold text-foreground">Filter by Specialty:</span>
            <Button
              variant={selectedSpecialty === null ? 'default' : 'outline'}
              size="sm"
              onClick={() => setSelectedSpecialty(null)}
              className="rounded-full"
            >
              All Experts
            </Button>
            {specialties.map((specialty) => {
              const Icon = SPECIALTY_ICONS[specialty as keyof typeof SPECIALTY_ICONS];
              return (
                <Button
                  key={specialty}
                  variant={selectedSpecialty === specialty ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setSelectedSpecialty(specialty)}
                  className="rounded-full flex items-center gap-2"
                >
                  <Icon className="w-4 h-4" />
                  {specialty}
                </Button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Experts Grid */}
      <div className="max-w-7xl mx-auto px-6 py-12">
        {filteredExperts.length === 0 ? (
          <div className="text-center py-16">
            <Search className="w-16 h-16 text-muted-foreground mx-auto mb-4 opacity-50" />
            <h3 className="text-xl font-semibold mb-2">No experts found</h3>
            <p className="text-muted-foreground">
              Try adjusting your search or filters
            </p>
          </div>
        ) : (
          <>
            <div className="flex items-center justify-between mb-6">
              <p className="text-muted-foreground">
                Showing {filteredExperts.length} expert{filteredExperts.length !== 1 ? 's' : ''}
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredExperts.map((expert) => {
                const Icon = SPECIALTY_ICONS[expert.specialty as keyof typeof SPECIALTY_ICONS];

                return (
                  <div
                    key={expert.id}
                    onClick={() => handleExpertClick(expert.id)}
                    className="bg-card border rounded-2xl overflow-hidden hover:shadow-lg transition-all duration-300 cursor-pointer group hover:scale-[1.02]"
                  >
                    {/* Expert Header */}
                    <div className="relative bg-gradient-to-br from-primary/10 to-purple-100 dark:from-primary/20 dark:to-purple-900/20 p-6">
                      <div className="flex items-start gap-4">
                        <div className="relative">
                          <img
                            src={expert.avatar}
                            alt={expert.name}
                            className="w-20 h-20 rounded-full border-4 border-white dark:border-gray-800 shadow-lg"
                          />
                          {expert.featured && (
                            <div className="absolute -top-1 -right-1 bg-yellow-500 rounded-full p-1">
                              <Award className="w-4 h-4 text-white" />
                            </div>
                          )}
                        </div>
                        <div className="flex-1 min-w-0">
                          <h3 className="font-bold text-lg mb-1 group-hover:text-primary transition-colors">
                            {expert.name}
                          </h3>
                          <p className="text-sm text-muted-foreground mb-2">
                            {expert.credentials}
                          </p>
                          <div className="flex items-center gap-1 text-yellow-500">
                            <Star className="w-4 h-4 fill-current" />
                            <span className="text-sm font-semibold text-foreground">
                              {expert.rating}
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Expert Body */}
                    <div className="p-6">
                      <div className="flex items-center gap-2 mb-3">
                        {Icon && <Icon className="w-4 h-4 text-primary" />}
                        <Badge variant="secondary" className="text-xs">
                          {expert.specialty}
                        </Badge>
                      </div>

                      <p className="text-sm text-muted-foreground mb-4 line-clamp-2">
                        {expert.shortBio}
                      </p>

                      {/* Stats */}
                      <div className="flex items-center gap-4 mb-4 text-xs text-muted-foreground">
                        <div className="flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          <span>{expert.yearsOfExperience} years</span>
                        </div>
                        {expert.totalVideos && (
                          <div className="flex items-center gap-1">
                            <Video className="w-3 h-3" />
                            <span>{expert.totalVideos} videos</span>
                          </div>
                        )}
                      </div>

                      {/* Expertise Tags */}
                      <div className="flex flex-wrap gap-1.5">
                        {expert.expertise.slice(0, 3).map((exp, index) => (
                          <Badge
                            key={index}
                            variant="outline"
                            className="text-xs border-primary/30 text-primary"
                          >
                            {exp}
                          </Badge>
                        ))}
                        {expert.expertise.length > 3 && (
                          <Badge variant="outline" className="text-xs">
                            +{expert.expertise.length - 3} more
                          </Badge>
                        )}
                      </div>
                    </div>

                    {/* Footer */}
                    <div className="px-6 pb-6">
                      <Button
                        className="w-full rounded-full group-hover:bg-primary group-hover:text-white transition-colors"
                        variant="outline"
                      >
                        View Profile
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default ExpertsPage;
