// src/pages/ForgotPasswordPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { Header, Footer } from '@/components/layout'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'
import { authService } from '@/services/auth.service'
import { useToast } from '@/composables/useToast'
import { ArrowLeft, Mail, Loader2 } from 'lucide-vue-next'

const router = useRouter()
const { toast } = useToast()

const email = ref('')
const isLoading = ref(false)
const isSubmitted = ref(false)

const handleSubmit = async () => {
  if (!email.value || isLoading.value) return
  
  isLoading.value = true
  
  try {
    await authService.forgotPassword(email.value)
    isSubmitted.value = true
    toast({ title: 'Email sent', description: 'Check your inbox for reset instructions' })
  } catch (err: any) {
    toast({ title: 'Error', description: err.message || 'Failed to send reset email', variant: 'destructive' })
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
    <Header />
    
    <main class="flex items-center justify-center px-4 py-16">
      <Card class="w-full max-w-md">
        <CardHeader>
          <button @click="router.back()" class="flex items-center text-muted-foreground hover:text-foreground mb-4">
            <ArrowLeft class="h-4 w-4 mr-2" />
            Back
          </button>
          <CardTitle>Forgot Password</CardTitle>
          <CardDescription>
            {{ isSubmitted ? 'Check your email for reset instructions' : "Enter your email and we'll send you a reset link" }}
          </CardDescription>
        </CardHeader>
        
        <CardContent>
          <div v-if="isSubmitted" class="text-center py-8">
            <Mail class="h-12 w-12 text-primary mx-auto mb-4" />
            <p class="text-muted-foreground">We've sent a reset link to {{ email }}</p>
          </div>
          
          <form v-else @submit.prevent="handleSubmit" class="space-y-4">
            <div class="space-y-2">
              <Label for="email">Email</Label>
              <Input id="email" v-model="email" type="email" placeholder="you@example.com" required />
            </div>
            <Button type="submit" class="w-full" :disabled="isLoading">
              <Loader2 v-if="isLoading" class="mr-2 h-4 w-4 animate-spin" />
              Send Reset Link
            </Button>
          </form>
        </CardContent>
      </Card>
    </main>
    
    <Footer />
  </div>
</template>

// src/pages/ForgotPasswordPage.tsx
// src/pages/ForgotPasswordPage.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { authService } from "@/services/auth.service";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Mail,
  ArrowLeft,
  AlertCircle,
  Loader2,
  CheckCircle2,
  Shield
} from "lucide-react";

const ForgotPasswordPage = () => {
  const [email, setEmail] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const [validationError, setValidationError] = useState("");

  // Email validation
  const validateEmail = (email: string) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!email) {
      return "Email is required";
    }
    if (!emailRegex.test(email)) {
      return "Please enter a valid email address";
    }
    return "";
  };

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setValidationError("");

    // Validate email
    const emailError = validateEmail(email);
    if (emailError) {
      setValidationError(emailError);
      return;
    }

    setIsLoading(true);

    try {
      await authService.forgotPassword(email);
      setSuccess(true);
    } catch (error: any) {
      console.error('Password reset request error:', error);
      setError(
        error.message ||
        "Could not process your request. Please try again."
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-indigo-50 via-white to-purple-50 px-4 py-12">
      <div className="w-full max-w-md">
        {/* Back to Login */}
        <Link
          to="/login"
          className="inline-flex items-center text-slate-600 hover:text-indigo-600 mb-6 transition-colors group"
        >
          <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" />
          <span className="font-medium">Back to login</span>
        </Link>

        {/* Card */}
        <div className="bg-white rounded-2xl shadow-xl border border-slate-200 p-8">
          {/* Header */}
          <div className="text-center mb-8">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-indigo-100 mb-4">
              <Shield className="w-8 h-8 text-indigo-600" />
            </div>
            <h1 className="text-3xl font-bold text-slate-900 mb-2">
              Reset Password
            </h1>
            <p className="text-slate-600">
              {success
                ? "Check your email for reset instructions"
                : "Enter your email address and we'll send you a link to reset your password"
              }
            </p>
          </div>

          {/* Success Message */}
          {success ? (
            <div className="space-y-6">
              <Alert className="border-green-200 bg-green-50">
                <CheckCircle2 className="h-5 w-5 text-green-600" />
                <AlertDescription className="text-green-800">
                  <strong className="font-semibold">Email sent successfully!</strong>
                  <br />
                  We've sent password reset instructions to <strong>{email}</strong>.
                  Please check your inbox and follow the link to reset your password.
                </AlertDescription>
              </Alert>

              <div className="bg-slate-50 rounded-xl border border-slate-200 p-4">
                <p className="text-sm text-slate-600 mb-2">
                  <strong className="font-semibold text-slate-700">Didn't receive the email?</strong>
                </p>
                <ul className="text-sm text-slate-600 space-y-1 list-disc list-inside">
                  <li>Check your spam or junk folder</li>
                  <li>Make sure you entered the correct email</li>
                  <li>Wait a few minutes and check again</li>
                </ul>
              </div>

              <Button
                onClick={() => {
                  setSuccess(false);
                  setEmail("");
                }}
                variant="outline"
                className="w-full h-12 rounded-xl border-2"
              >
                Send another email
              </Button>

              <div className="text-center">
                <Link
                  to="/login"
                  className="text-indigo-600 hover:text-indigo-500 font-semibold transition-colors"
                >
                  Return to login
                </Link>
              </div>
            </div>
          ) : (
            <>
              {/* Error Alert */}
              {error && (
                <Alert variant="destructive" className="mb-6 border-red-200 bg-red-50">
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription className="text-red-800">{error}</AlertDescription>
                </Alert>
              )}

              {/* Form */}
              <form onSubmit={handleSubmit} className="space-y-6">
                <div className="space-y-2">
                  <Label htmlFor="email" className="text-slate-700 font-medium">
                    Email Address
                  </Label>
                  <div className="relative">
                    <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400 w-5 h-5" />
                    <Input
                      id="email"
                      type="email"
                      placeholder="Enter your email address"
                      value={email}
                      onChange={(e) => {
                        setEmail(e.target.value);
                        setValidationError("");
                      }}
                      className={`pl-11 h-12 rounded-xl border-2 transition-all focus:border-indigo-500 ${
                        validationError ? 'border-red-300 focus:border-red-500' : 'border-slate-200'
                      }`}
                      disabled={isLoading}
                      required
                    />
                  </div>
                  {validationError && (
                    <p className="text-red-600 text-sm font-medium">{validationError}</p>
                  )}
                </div>

                <Button
                  type="submit"
                  className="w-full h-12 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white font-semibold shadow-lg hover:shadow-xl transition-all duration-300"
                  disabled={isLoading}
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                      Sending reset link...
                    </>
                  ) : (
                    <>
                      Send reset link
                    </>
                  )}
                </Button>
              </form>

              {/* Security Notice */}
              <div className="mt-6 bg-slate-50 rounded-xl border border-slate-200 p-4">
                <p className="text-xs text-slate-600 text-center leading-relaxed">
                  For security reasons, we'll send a password reset link that expires in 1 hour.
                  If you don't receive an email, please check your spam folder or contact support.
                </p>
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="text-center mt-6">
          <p className="text-slate-600 text-sm">
            Need help?{" "}
            <Link
              to="/support"
              className="text-indigo-600 hover:text-indigo-500 font-medium transition-colors"
            >
              Contact support
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default ForgotPasswordPage;
