// src/pages/LoginPage.tsx
// src/pages/LoginPage.tsx
import { useState } from "react";
import { useNavigate, useLocation, Link } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { 
  Eye, 
  EyeOff, 
  Mail, 
  Lock, 
  User,
  Sparkles, 
  ArrowLeft,
  AlertCircle,
  Loader2,
  Github,
  Chrome
} from "lucide-react";
import betterBlissLogo from "@/assets/betterandblisslogo.png";
import { authService } from "@/services/auth.service";

const LoginPage = () => {
  // State for form inputs
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [fullName, setFullName] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  
  // UI state
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [mode, setMode] = useState<'signin' | 'signup'>('signin');
  const [rememberMe, setRememberMe] = useState(false);
  const [error, setError] = useState("");
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({});
  
  // Hooks
  const { login, register } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  
  // Get the page user was trying to access
  const from = location.state?.from?.pathname || "/";

  // Form validation
  const validateForm = () => {
    const errors: Record<string, string> = {};
    
    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!email) {
      errors.email = "Email is required";
    } else if (!emailRegex.test(email)) {
      errors.email = "Please enter a valid email address";
    }
    
    // Password validation
    if (!password) {
      errors.password = "Password is required";
    } else if (mode === 'signup' && password.length < 8) {
      errors.password = "Password must be at least 8 characters";
    }
    
    // Sign up specific validations
    if (mode === 'signup') {
      if (!fullName.trim()) {
        errors.fullName = "Full name is required";
      }
      
      if (!confirmPassword) {
        errors.confirmPassword = "Please confirm your password";
      } else if (password !== confirmPassword) {
        errors.confirmPassword = "Passwords do not match";
      }
    }
    
    setValidationErrors(errors);
    return Object.keys(errors).length === 0;
  };

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    
    if (!validateForm()) {
      return;
    }
    
    setIsLoading(true);
    
    try {
      if (mode === 'signin') {
        await login(email, password);
        // Navigate to the page they were trying to access, or home
        navigate(from, { replace: true });
      } else {
        await register(email, password, fullName);
        // After signup, go to home or dashboard
        navigate('/browse', { replace: true });
      }
    } catch (error: any) {
      console.error('Auth error:', error);
      setError(
        error.response?.data?.detail || 
        mode === 'signin' 
          ? "Invalid email or password. Please try again."
          : "Could not create account. Please try again."
      );
    } finally {
      setIsLoading(false);
    }
  };

  // Handle social login
  const handleGoogleLogin = () => {
    setIsLoading(true);
    authService.loginWithGoogle();
  };

  const handleGithubLogin = () => {
    // Implement GitHub OAuth if needed
    console.log("GitHub login not implemented yet");
  };

  // Clear errors when switching modes
  const switchMode = () => {
    setMode(mode === 'signin' ? 'signup' : 'signin');
    setError("");
    setValidationErrors({});
    setPassword("");
    setConfirmPassword("");
  };

  return (
    <div className="min-h-screen bg-gradient-secondary flex items-center justify-center p-4 relative overflow-hidden">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -left-40 w-[800px] h-[600px] bg-gradient-to-br from-primary/10 to-purple-400/5 rounded-[40%_60%_70%_30%] blur-3xl animate-pulse rotate-12"></div>
        <div className="absolute -bottom-32 -right-32 w-[700px] h-[500px] bg-gradient-to-tl from-purple-500/10 to-primary/5 rounded-[60%_40%_30%_70%] blur-3xl animate-pulse delay-1000 -rotate-12"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] bg-gradient-to-r from-primary/5 to-transparent rounded-[50%_30%_70%_50%] blur-2xl animate-pulse delay-500 rotate-45"></div>
      </div>

      <div className="w-full max-w-md relative z-10">
        {/* Back to Home Link */}
        <Link 
          to="/" 
          className="inline-flex items-center text-muted-foreground hover:text-foreground mb-6 transition-colors"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>

        {/* Main Card */}
        <Card className="shadow-glow border-border/50">
          <CardHeader className="text-center space-y-1 pb-4">
            {/* Logo */}
            <div className="mx-auto mb-4 relative">
              <img 
                src={betterBlissLogo} 
                alt="Better & Bliss" 
                className="w-20 h-20 rounded-3xl shadow-soft"
              />
              <div className="absolute -bottom-1 -right-1 w-6 h-6 bg-gradient-primary rounded-full flex items-center justify-center">
                <Sparkles className="w-3 h-3 text-white" />
              </div>
            </div>
            
            <CardTitle className="text-3xl font-bold bg-gradient-primary bg-clip-text text-transparent">
              {mode === 'signin' ? 'Welcome Back' : 'Join Better & Bliss'}
            </CardTitle>
            <CardDescription className="text-muted-foreground">
              {mode === 'signin' 
                ? 'Sign in to continue your wellness journey' 
                : 'Create an account to start your transformation'
              }
            </CardDescription>
          </CardHeader>
          
          <CardContent className="space-y-4">
            {/* Error Alert */}
            {error && (
              <Alert variant="destructive" className="mb-4">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}

            {/* Form */}
            <form onSubmit={handleSubmit} className="space-y-4">
              {/* Full Name (Sign up only) */}
              {mode === 'signup' && (
                <div className="space-y-2">
                  <Label htmlFor="fullName">Full Name</Label>
                  <div className="relative">
                    <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                    <Input
                      id="fullName"
                      type="text"
                      placeholder="John Doe"
                      value={fullName}
                      onChange={(e) => setFullName(e.target.value)}
                      className={`pl-10 ${validationErrors.fullName ? 'border-red-500' : ''}`}
                      disabled={isLoading}
                      required
                    />
                  </div>
                  {validationErrors.fullName && (
                    <p className="text-red-500 text-sm">{validationErrors.fullName}</p>
                  )}
                </div>
              )}
              
              {/* Email */}
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                  <Input
                    id="email"
                    type="email"
                    placeholder="you@example.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className={`pl-10 ${validationErrors.email ? 'border-red-500' : ''}`}
                    disabled={isLoading}
                    required
                  />
                </div>
                {validationErrors.email && (
                  <p className="text-red-500 text-sm">{validationErrors.email}</p>
                )}
              </div>
              
              {/* Password */}
              <div className="space-y-2">
                <div className="flex justify-between">
                  <Label htmlFor="password">Password</Label>
                  {mode === 'signin' && (
                    <Link 
                      to="/forgot-password" 
                      className="text-sm text-primary hover:underline"
                    >
                      Forgot password?
                    </Link>
                  )}
                </div>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                  <Input
                    id="password"
                    type={showPassword ? "text" : "password"}
                    placeholder={mode === 'signin' ? "Enter your password" : "Create a password"}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className={`pl-10 pr-10 ${validationErrors.password ? 'border-red-500' : ''}`}
                    disabled={isLoading}
                    required
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3 top-1/2 transform -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                    tabIndex={-1}
                  >
                    {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>
                {validationErrors.password && (
                  <p className="text-red-500 text-sm">{validationErrors.password}</p>
                )}
                {mode === 'signup' && (
                  <p className="text-xs text-muted-foreground">
                    Must be at least 8 characters long
                  </p>
                )}
              </div>
              
              {/* Confirm Password (Sign up only) */}
              {mode === 'signup' && (
                <div className="space-y-2">
                  <Label htmlFor="confirmPassword">Confirm Password</Label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                    <Input
                      id="confirmPassword"
                      type={showConfirmPassword ? "text" : "password"}
                      placeholder="Confirm your password"
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                      className={`pl-10 pr-10 ${validationErrors.confirmPassword ? 'border-red-500' : ''}`}
                      disabled={isLoading}
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                      className="absolute right-3 top-1/2 transform -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                      tabIndex={-1}
                    >
                      {showConfirmPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    </button>
                  </div>
                  {validationErrors.confirmPassword && (
                    <p className="text-red-500 text-sm">{validationErrors.confirmPassword}</p>
                  )}
                </div>
              )}
              
              {/* Remember Me (Sign in only) */}
              {mode === 'signin' && (
                <div className="flex items-center space-x-2">
                  <Checkbox 
                    id="remember" 
                    checked={rememberMe}
                    onCheckedChange={(checked) => setRememberMe(checked as boolean)}
                  />
                  <Label 
                    htmlFor="remember" 
                    className="text-sm font-normal cursor-pointer"
                  >
                    Remember me for 30 days
                  </Label>
                </div>
              )}
              
              {/* Submit Button */}
              <Button 
                type="submit" 
                className="w-full h-11" 
                disabled={isLoading}
              >
                {isLoading ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    {mode === 'signin' ? 'Signing in...' : 'Creating account...'}
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 mr-2" />
                    {mode === 'signin' ? 'Sign In' : 'Create Account'}
                  </>
                )}
              </Button>
            </form>
            
            {/* Divider */}
            <div className="relative my-6">
              <div className="absolute inset-0 flex items-center">
                <Separator className="w-full" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-card px-2 text-muted-foreground">Or continue with</span>
              </div>
            </div>
            
            {/* Social Login Buttons */}
            <div className="grid grid-cols-2 gap-4">
              <Button 
                type="button"
                variant="outline" 
                onClick={handleGoogleLogin}
                disabled={isLoading}
                className="h-11"
              >
                <Chrome className="w-4 h-4 mr-2" />
                Google
              </Button>
              <Button 
                type="button"
                variant="outline" 
                onClick={handleGithubLogin}
                disabled={isLoading}
                className="h-11"
              >
                <Github className="w-4 h-4 mr-2" />
                GitHub
              </Button>
            </div>
            
            {/* Switch Mode */}
            <div className="text-center text-sm mt-6">
              <span className="text-muted-foreground">
                {mode === 'signin' ? "Don't have an account? " : "Already have an account? "}
              </span>
              <button
                type="button"
                onClick={switchMode}
                className="text-primary hover:underline font-medium"
                disabled={isLoading}
              >
                {mode === 'signin' ? 'Sign up' : 'Sign in'}
              </button>
            </div>
            
            {/* Terms and Privacy (Sign up only) */}
            {mode === 'signup' && (
              <p className="text-xs text-center text-muted-foreground mt-4">
                By creating an account, you agree to our{' '}
                <Link to="/terms" className="text-primary hover:underline">
                  Terms of Service
                </Link>{' '}
                and{' '}
                <Link to="/privacy" className="text-primary hover:underline">
                  Privacy Policy
                </Link>
              </p>
            )}
          </CardContent>
        </Card>
        
        {/* Additional Info */}
        <div className="text-center mt-6 text-sm text-muted-foreground">
          <p>Need help? <Link to="/support" className="text-primary hover:underline">Contact Support</Link></p>
        </div>
      </div>
    </div>
  );
};

export default LoginPage;

// src/pages/LoginPage.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'
import { Header, Footer } from '@/components/layout'
import { Eye, EyeOff, Loader2, Mail, Lock } from 'lucide-vue-next'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()

const email = ref('')
const password = ref('')
const showPassword = ref(false)
const isLoading = ref(false)
const error = ref('')
const isRegisterMode = ref(false)
const fullName = ref('')

const redirectPath = computed(() => route.query.redirect as string || '/browse')

const toggleMode = () => {
  isRegisterMode.value = !isRegisterMode.value
  error.value = ''
}

const handleSubmit = async () => {
  if (isLoading.value) return
  
  error.value = ''
  isLoading.value = true
  
  try {
    if (isRegisterMode.value) {
      const result = await authStore.register(email.value, password.value, fullName.value)
      if (result?.needsConfirmation) {
        // Stay on login page, show confirmation message
        isRegisterMode.value = false
        return
      }
    } else {
      await authStore.login(email.value, password.value)
    }
    
    router.push(redirectPath.value)
  } catch (err: any) {
    error.value = err.message || 'An error occurred'
  } finally {
    isLoading.value = false
  }
}

const handleGoogleLogin = async () => {
  try {
    // Redirect to Google OAuth
    window.location.href = `${import.meta.env.VITE_API_URL}/auth/google`
  } catch (err: any) {
    error.value = err.message || 'Google login failed'
  }
}
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
    <Header />
    
    <main class="flex items-center justify-center px-4 py-16">
      <Card class="w-full max-w-md">
        <CardHeader class="text-center">
          <CardTitle class="text-2xl">
            {{ isRegisterMode ? 'Create Account' : 'Welcome Back' }}
          </CardTitle>
          <CardDescription>
            {{ isRegisterMode 
              ? 'Start your transformation journey today' 
              : 'Sign in to continue your journey' 
            }}
          </CardDescription>
        </CardHeader>
        
        <CardContent>
          <form @submit.prevent="handleSubmit" class="space-y-4">
            <!-- Error Message -->
            <div
              v-if="error"
              class="p-3 rounded-md bg-destructive/10 text-destructive text-sm"
            >
              {{ error }}
            </div>
            
            <!-- Full Name (Register only) -->
            <div v-if="isRegisterMode" class="space-y-2">
              <Label for="fullName">Full Name</Label>
              <Input
                id="fullName"
                v-model="fullName"
                placeholder="Enter your name"
                required
                :disabled="isLoading"
              />
            </div>
            
            <!-- Email -->
            <div class="space-y-2">
              <Label for="email">Email</Label>
              <div class="relative">
                <Mail class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="email"
                  v-model="email"
                  type="email"
                  placeholder="you@example.com"
                  required
                  :disabled="isLoading"
                  class="pl-10"
                />
              </div>
            </div>
            
            <!-- Password -->
            <div class="space-y-2">
              <Label for="password">Password</Label>
              <div class="relative">
                <Lock class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  id="password"
                  v-model="password"
                  :type="showPassword ? 'text' : 'password'"
                  placeholder="••••••••"
                  required
                  :disabled="isLoading"
                  class="pl-10 pr-10"
                />
                <button
                  type="button"
                  class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  @click="showPassword = !showPassword"
                >
                  <Eye v-if="!showPassword" class="h-4 w-4" />
                  <EyeOff v-else class="h-4 w-4" />
                </button>
              </div>
            </div>
            
            <!-- Forgot Password Link -->
            <div v-if="!isRegisterMode" class="text-right">
              <RouterLink
                to="/forgot-password"
                class="text-sm text-primary hover:underline"
              >
                Forgot password?
              </RouterLink>
            </div>
            
            <!-- Submit Button -->
            <Button
              type="submit"
              class="w-full"
              :disabled="isLoading"
            >
              <Loader2 v-if="isLoading" class="mr-2 h-4 w-4 animate-spin" />
              {{ isRegisterMode ? 'Create Account' : 'Sign In' }}
            </Button>
          </form>
          
          <!-- Divider -->
          <div class="relative my-6">
            <div class="absolute inset-0 flex items-center">
              <div class="w-full border-t" />
            </div>
            <div class="relative flex justify-center text-xs uppercase">
              <span class="bg-card px-2 text-muted-foreground">Or continue with</span>
            </div>
          </div>
          
          <!-- Social Login -->
          <Button
            variant="outline"
            class="w-full"
            @click="handleGoogleLogin"
            :disabled="isLoading"
          >
            <svg class="mr-2 h-4 w-4" viewBox="0 0 24 24">
              <path
                fill="currentColor"
                d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
              />
              <path
                fill="currentColor"
                d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
              />
              <path
                fill="currentColor"
                d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
              />
              <path
                fill="currentColor"
                d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
              />
            </svg>
            Continue with Google
          </Button>
        </CardContent>
        
        <CardFooter class="justify-center">
          <p class="text-sm text-muted-foreground">
            {{ isRegisterMode ? 'Already have an account?' : "Don't have an account?" }}
            <button
              type="button"
              class="text-primary hover:underline ml-1"
              @click="toggleMode"
            >
              {{ isRegisterMode ? 'Sign In' : 'Sign Up' }}
            </button>
          </p>
        </CardFooter>
      </Card>
    </main>
    
    <Footer />
  </div>
</template>
