// src/pages/UnauthorizedPage.tsx
// src/pages/UnauthorizedPage.tsx
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ShieldX } from "lucide-react";

const UnauthorizedPage = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-secondary flex items-center justify-center p-4">
      <div className="text-center">
        <ShieldX className="w-24 h-24 text-red-500 mx-auto mb-6" />
        <h1 className="text-4xl font-bold mb-4">Unauthorized Access</h1>
        <p className="text-xl text-muted-foreground mb-8">
          You don't have permission to access this page.
        </p>
        <div className="space-x-4">
          <Button onClick={() => navigate('/')}>
            Go Home
          </Button>
          <Button variant="outline" onClick={() => navigate(-1)}>
            Go Back
          </Button>
        </div>
      </div>
    </div>
  );
};

export default UnauthorizedPage;

// src/pages/UnauthorizedPage.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { Button } from '@/components/ui/button'
import { ShieldX, Home, LogIn } from 'lucide-vue-next'
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-50 to-gray-100 px-4">
    <div class="text-center max-w-md">
      <div class="flex justify-center mb-6">
        <div class="p-4 rounded-full bg-destructive/10">
          <ShieldX class="h-12 w-12 text-destructive" />
        </div>
      </div>
      <h1 class="text-2xl font-semibold text-gray-900 mb-2">
        Access Denied
      </h1>
      <p class="text-gray-600 mb-8">
        You don't have permission to access this page. Please sign in with an authorized account.
      </p>
      <div class="flex flex-col sm:flex-row gap-3 justify-center">
        <RouterLink to="/">
          <Button variant="outline">
            <Home class="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </RouterLink>
        <RouterLink to="/login">
          <Button>
            <LogIn class="mr-2 h-4 w-4" />
            Sign In
          </Button>
        </RouterLink>
      </div>
    </div>
  </div>
</template>
