// src/pages/WatchPage.tsx
// src/pages/WatchPage.tsx - FIXED VERSION WITH BETTER ERROR HANDLING
import { useParams, useNavigate } from 'react-router-dom';
import { useRef, useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import HLSVideoPlayer, { HLSVideoPlayerRef } from '@/components/VideoModal/HLSVideoPlayer';
import { contentService } from '@/services/content.service';
import { Video, isUUID } from '@/types/video.types';
import { toast } from 'sonner';
import { analyticsService } from '@/services/analytics.service';
import {
  X, Plus, ThumbsUp, Share2, Check, Loader2, AlertCircle, ArrowLeft, RefreshCw,
  PlayCircle, Clock, BookOpen, Hash, ChevronRight
} from 'lucide-react';

const WatchPage = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const videoRef = useRef<HLSVideoPlayerRef>(null);

  const [video, setVideo] = useState<Video | null>(null);
  const [streamUrl, setStreamUrl] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [retrying, setRetrying] = useState(false);
  const [activeTab, setActiveTab] = useState('overview');
  const [copied, setCopied] = useState(false);
  const [viewTracked, setViewTracked] = useState(false);
  const [relatedVideos, setRelatedVideos] = useState<Video[]>([]);
  const [seriesEpisodes, setSeriesEpisodes] = useState<Video[]>([]);

  // Debug info
  const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:8000';

  const fetchVideo = async (isRetry = false) => {
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('🎬 WatchPage - Fetching Video');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('📍 Video ID:', id);
    console.log('🌐 API URL:', apiUrl);
    console.log('🔄 Is Retry:', isRetry);
    
    if (!id) {
      console.error('❌ No video ID provided');
      setError('No video ID provided');
      setLoading(false);
      return;
    }

    if (!isUUID(id)) {
      console.error('❌ Invalid UUID format:', id);
      setError('Invalid video ID format');
      setLoading(false);
      return;
    }

    try {
      if (isRetry) {
        setRetrying(true);
      } else {
        setLoading(true);
      }
      setError(null);

      console.log('📥 Step 1: Fetching video metadata...');
      const videoData = await contentService.getVideoByUUID(id);
      console.log('✅ Video metadata loaded:', {
        id: videoData.id,
        title: videoData.title,
        accessTier: videoData.accessTier
      });
      setVideo(videoData);

      console.log('📥 Step 2: Fetching stream data...');
      const streamData = await contentService.getVideoStreamData(id);
      console.log('✅ Stream data loaded:', {
        streamUrl: streamData.streamUrl ? 'Present' : 'Missing',
        qualities: streamData.qualities,
        thumbnailUrl: streamData.thumbnailUrl ? 'Present' : 'Missing'
      });

      if (!streamData.streamUrl) {
        throw new Error('No stream URL returned from server');
      }

      setStreamUrl(streamData.streamUrl);
      console.log('✅ Video loaded successfully');

      // Track view when stream loads successfully
      await trackVideoView(videoData);

    } catch (err: any) {
      console.error('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      console.error('❌ ERROR FETCHING VIDEO');
      console.error('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      console.error('Error:', err);
      console.error('Error message:', err.message);
      console.error('Error response:', err.response?.data);
      console.error('Error status:', err.response?.status);
      console.error('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      
      setError(err.message || 'Failed to load video');
      
      // Show toast with helpful message
      if (err.message.includes('not found')) {
        toast.error('Video not found');
      } else if (err.message.includes('Access denied')) {
        toast.error('Upgrade required to watch this video');
      } else {
        toast.error('Failed to load video. Please try again.');
      }
      
    } finally {
      setLoading(false);
      setRetrying(false);
    }
  };

  // Track video view (call once when video starts)
  const trackVideoView = useCallback(async (videoData: Video) => {
    if (viewTracked || !videoData?.id) return;

    try {
      // Generate or get session ID
      const sessionId = sessionStorage.getItem('sessionId') ||
        (() => {
          const id = crypto.randomUUID();
          sessionStorage.setItem('sessionId', id);
          return id;
        })();

      await analyticsService.trackView({
        content_id: videoData.id,
        video_title: videoData.title,
        category: videoData.category_name || videoData.category,
        expert: videoData.expert,
        duration_seconds: videoData.duration_seconds,
        session_id: sessionId
      });

      setViewTracked(true);
      console.log('✅ Video view tracked:', videoData.title);
    } catch (error) {
      console.error('❌ Failed to track video view:', error);
    }
  }, [viewTracked]);

  // Fetch related videos and next episode
  const fetchRelatedContent = useCallback(async (currentVideo: Video) => {
    try {
      // Fetch videos from the same category
      const allVideos = await contentService.getVideosForFrontend(currentVideo.category);

      // Filter out current video and get random 6
      const related = allVideos
        .filter(v => v.id !== currentVideo.id)
        .slice(0, 6);

      setRelatedVideos(related);

      // If video is part of a series, find the next episode
      if (currentVideo.series_id || currentVideo.seriesId) {
        const seriesId = currentVideo.series_id || currentVideo.seriesId;
        const currentEpisodeNum = currentVideo.episode_number || currentVideo.episodeNumber || 0;

        const allSeriesEpisodes = allVideos
          .filter(v => (v.series_id || v.seriesId) === seriesId)
          .sort((a, b) => {
            const aEp = a.episode_number || a.episodeNumber || 0;
            const bEp = b.episode_number || b.episodeNumber || 0;
            return aEp - bEp;
          });

        // Find next episode only
        const nextEpisode = allSeriesEpisodes.find(ep => {
          const epNum = ep.episode_number || ep.episodeNumber || 0;
          return epNum > currentEpisodeNum;
        });

        setSeriesEpisodes(nextEpisode ? [nextEpisode] : []);
      }
    } catch (error) {
      console.error('Failed to fetch related content:', error);
    }
  }, []);

  useEffect(() => {
    fetchVideo();
  }, [id]);

  // Fetch related content when video loads
  useEffect(() => {
    if (video) {
      fetchRelatedContent(video);
    }
  }, [video, fetchRelatedContent]);

  const handleRetry = () => {
    fetchVideo(true);
  };

  const handleCopyLink = () => {
    if (!video) return;

    const shareUrl = `${window.location.origin}/watch/${video.id}`;

    navigator.clipboard.writeText(shareUrl)
      .then(() => {
        setCopied(true);
        toast.success('Link copied to clipboard!');
        setTimeout(() => setCopied(false), 2000);
      })
      .catch(() => {
        toast.error('Failed to copy link');
      });
  };

  // Loading state
  if (loading) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center">
        <div className="text-center space-y-4">
          <Loader2 className="w-12 h-12 text-purple-500 animate-spin mx-auto" />
          <p className="text-gray-400">Loading video...</p>
          <p className="text-xs text-gray-600">
            Video ID: {id}
          </p>
        </div>
      </div>
    );
  }

  // Error state with retry option
  if (error || !video) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center px-4">
        <div className="text-center max-w-md space-y-6">
          <AlertCircle className="w-16 h-16 text-red-500 mx-auto" />
          
          <div>
            <h2 className="text-2xl font-bold text-white mb-2">
              {error || 'Video not found'}
            </h2>
            <p className="text-gray-400 mb-2">
              The video you're looking for doesn't exist or has been removed.
            </p>
          </div>

          {/* Debug Info */}
          <div className="bg-gray-900 p-4 rounded-lg text-left text-xs text-gray-500 space-y-1">
            <p className="font-bold text-gray-400 mb-2">Debug Info:</p>
            <p>Video ID: {id}</p>
            <p>Error: {error || 'Unknown error'}</p>
            <p>API URL: {apiUrl}</p>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3 justify-center">
            <Button
              onClick={handleRetry}
              disabled={retrying}
              variant="outline"
              className="border-gray-700 text-white hover:bg-gray-800"
            >
              {retrying ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Retrying...
                </>
              ) : (
                <>
                  <RefreshCw className="w-4 h-4 mr-2" />
                  Try Again
                </>
              )}
            </Button>
            
            <Button
              onClick={() => navigate('/browse')}
              variant="outline"
              className="border-gray-700 text-white hover:bg-gray-800"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Browse
            </Button>
          </div>
        </div>
      </div>
    );
  }

  // Success - render video player
  return (
    <div className="min-h-screen bg-black">
      {/* Close Button */}
      <div className="relative">
        <Button
          variant="ghost"
          size="icon"
          onClick={() => navigate('/browse')}
          className="absolute top-4 left-4 z-50 rounded-full bg-black/60 hover:bg-black/80 text-white"
        >
          <X className="w-5 h-5" />
        </Button>

        {/* Video Player */}
        <div className="relative w-full aspect-video bg-black max-w-[1920px] mx-auto">
          {streamUrl ? (
            <HLSVideoPlayer
              ref={videoRef}
              src={streamUrl}
              poster={video.thumbnail}
              className="w-full h-full"
              autoPlay={true}
            />
          ) : (
            <div className="absolute inset-0 flex items-center justify-center bg-black">
              <div className="text-center text-white">
                <AlertCircle className="w-12 h-12 mx-auto mb-4" />
                <p>No stream URL available</p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Video Info */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        <h1 className="text-3xl font-bold text-white mb-4">{video.title}</h1>
        
        <div className="flex items-center gap-4 mb-6">
          <img
            src={video.expertAvatar}
            alt={video.expert}
            className="w-12 h-12 rounded-full"
          />
          <div>
            <p className="text-white font-semibold">{video.expert}</p>
            {video.expertCredentials && (
              <p className="text-gray-400 text-sm">{video.expertCredentials}</p>
            )}
          </div>
        </div>

        <div className="flex gap-2 mb-6">
          <Badge variant="outline" className="border-gray-700 text-gray-300">
            {video.category}
          </Badge>
          {video.isNew && (
            <Badge className="bg-purple-600 text-white">New</Badge>
          )}
        </div>

        <p className="text-gray-300 leading-relaxed mb-6">
          {video.fullDescription || video.description}
        </p>

        {/* Action Buttons */}
        <div className="flex gap-3 mb-8">
          <Button
            onClick={handleCopyLink}
            variant="outline"
            className="border-gray-700 text-white hover:bg-gray-800"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 mr-2" />
                Copied!
              </>
            ) : (
              <>
                <Share2 className="w-4 h-4 mr-2" />
                Share
              </>
            )}
          </Button>

          <Button
            variant="outline"
            className="border-gray-700 text-white hover:bg-gray-800"
          >
            <Plus className="w-4 h-4 mr-2" />
            Add to List
          </Button>

          <Button
            variant="outline"
            className="border-gray-700 text-white hover:bg-gray-800"
          >
            <ThumbsUp className="w-4 h-4 mr-2" />
            Like
          </Button>
        </div>

        {/* Content Sections */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left Column - Main Content */}
          <div className="lg:col-span-2 space-y-6">
            {/* Learning Objectives */}
            {video.learningObjectives && video.learningObjectives.length > 0 && (
              <Card className="bg-gray-900 border-gray-800">
                <CardHeader>
                  <CardTitle className="text-white flex items-center gap-2">
                    <BookOpen className="w-5 h-5 text-purple-500" />
                    What You'll Learn
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {video.learningObjectives.map((objective, index) => (
                      <li key={index} className="text-gray-300 flex items-start gap-2">
                        <Check className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                        <span>{objective}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            )}

            {/* Related Topics */}
            {video.relatedTopics && video.relatedTopics.length > 0 && (
              <Card className="bg-gray-900 border-gray-800">
                <CardHeader>
                  <CardTitle className="text-white flex items-center gap-2">
                    <Hash className="w-5 h-5 text-purple-500" />
                    Related Topics
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {video.relatedTopics.map((topic, index) => (
                      <Badge
                        key={index}
                        variant="outline"
                        className="border-purple-500/50 text-purple-300 hover:bg-purple-500/10 cursor-pointer"
                      >
                        {topic}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Next Episode */}
            {seriesEpisodes.length > 0 && (
              <Card className="bg-gray-900 border-gray-800 hover:border-purple-500/50 transition-all">
                <CardHeader className="pb-3">
                  <CardTitle className="text-white text-base font-medium">
                    Next Episode
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-0">
                  {seriesEpisodes.map((episode) => {
                    const episodeNum = episode.episode_number || episode.episodeNumber;

                    return (
                      <div
                        key={episode.id}
                        onClick={() => navigate(`/watch/${episode.id}`)}
                        className="cursor-pointer group"
                      >
                        <div className="relative overflow-hidden">
                          <img
                            src={episode.thumbnail}
                            alt={episode.title}
                            className="w-full aspect-video object-cover transition-transform duration-300 group-hover:scale-105"
                          />
                          {episodeNum && (
                            <Badge className="absolute top-3 left-3 bg-black/80 text-white">
                              Episode {episodeNum}
                            </Badge>
                          )}
                          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                            <div className="bg-purple-600 rounded-full p-4">
                              <PlayCircle className="w-12 h-12 text-white" />
                            </div>
                          </div>
                        </div>
                        <div className="p-4">
                          <h3 className="text-white font-semibold text-lg mb-2 group-hover:text-purple-400 transition-colors">
                            {episode.title}
                          </h3>
                          <p className="text-gray-400 text-sm line-clamp-2 mb-3">
                            {episode.description}
                          </p>
                          <div className="flex items-center gap-4 text-sm text-gray-500">
                            <span className="flex items-center gap-1">
                              <Clock className="w-4 h-4" />
                              {episode.duration}
                            </span>
                            {episode.views && (
                              <span>{episode.views} views</span>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </CardContent>
              </Card>
            )}
          </div>

          {/* Right Column - Related Videos */}
          <div className="lg:col-span-1">
            {relatedVideos.length > 0 && (
              <Card className="bg-gray-900 border-gray-800">
                <CardHeader>
                  <CardTitle className="text-white">More Like This</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {relatedVideos.map((relatedVideo) => (
                      <div
                        key={relatedVideo.id}
                        onClick={() => navigate(`/watch/${relatedVideo.id}`)}
                        className="group cursor-pointer"
                      >
                        <div className="relative mb-2 overflow-hidden rounded-lg">
                          <img
                            src={relatedVideo.thumbnail}
                            alt={relatedVideo.title}
                            className="w-full h-32 object-cover transition-transform group-hover:scale-105"
                          />
                          <div className="absolute bottom-2 right-2 bg-black/80 text-white text-xs px-2 py-1 rounded">
                            {relatedVideo.duration}
                          </div>
                        </div>
                        <h4 className="text-white font-medium text-sm mb-1 line-clamp-2 group-hover:text-purple-400 transition-colors">
                          {relatedVideo.title}
                        </h4>
                        <p className="text-gray-400 text-xs mb-1">{relatedVideo.expert}</p>
                        <div className="flex items-center gap-2 text-xs text-gray-500">
                          <span>{relatedVideo.views} views</span>
                          {relatedVideo.isNew && (
                            <Badge className="bg-purple-600 text-white text-xs">New</Badge>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default WatchPage;

// src/pages/WatchPage.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { contentService } from '@/services/content.service'
import { useAuthStore } from '@/stores/auth'
import { Button } from '@/components/ui/button'
import Hls from 'hls.js'
import {
  ArrowLeft,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  SkipBack,
  SkipForward,
  Settings,
  Loader2,
  Clock,
  User,
  Star,
  ChevronRight,
  List
} from 'lucide-vue-next'

interface ContentDetail {
  id: string
  title: string
  description: string
  thumbnail_url?: string
  video_url?: string
  videoUrl?: string
  hls_url?: string
  duration_seconds: number
  expert_name: string
  expert_title?: string
  category_name: string
  access_tier: 'free' | 'premium'
  series_id?: string
  episode_number?: number
  view_count?: number
}

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const content = ref<ContentDetail | null>(null)
const loading = ref(true)
const error = ref('')
const videoRef = ref<HTMLVideoElement | null>(null)
const containerRef = ref<HTMLElement | null>(null)
const hls = ref<Hls | null>(null)

// Player state
const isPlaying = ref(false)
const isMuted = ref(false)
const isFullscreen = ref(false)
const currentTime = ref(0)
const duration = ref(0)
const volume = ref(1)
const showControls = ref(true)
const isBuffering = ref(false)
const showEpisodes = ref(false)
const relatedContent = ref<any[]>([])

let controlsTimeout: ReturnType<typeof setTimeout> | null = null
let progressInterval: ReturnType<typeof setInterval> | null = null

const progress = computed(() => {
  if (duration.value === 0) return 0
  return (currentTime.value / duration.value) * 100
})

const formattedCurrentTime = computed(() => formatTime(currentTime.value))
const formattedDuration = computed(() => formatTime(duration.value))

const formatTime = (seconds: number) => {
  const hrs = Math.floor(seconds / 3600)
  const mins = Math.floor((seconds % 3600) / 60)
  const secs = Math.floor(seconds % 60)
  
  if (hrs > 0) {
    return `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`
}

const togglePlay = () => {
  if (!videoRef.value) return
  
  if (isPlaying.value) {
    videoRef.value.pause()
  } else {
    videoRef.value.play()
  }
}

const toggleMute = () => {
  if (!videoRef.value) return
  videoRef.value.muted = !videoRef.value.muted
  isMuted.value = videoRef.value.muted
}

const toggleFullscreen = async () => {
  if (!containerRef.value) return
  
  try {
    if (document.fullscreenElement) {
      await document.exitFullscreen()
      isFullscreen.value = false
    } else {
      await containerRef.value.requestFullscreen()
      isFullscreen.value = true
    }
  } catch (err) {
    console.error('Fullscreen error:', err)
  }
}

const seek = (event: MouseEvent) => {
  if (!videoRef.value) return
  const target = event.currentTarget as HTMLElement
  const rect = target.getBoundingClientRect()
  const percent = (event.clientX - rect.left) / rect.width
  videoRef.value.currentTime = percent * duration.value
}

const skipForward = () => {
  if (!videoRef.value) return
  videoRef.value.currentTime = Math.min(videoRef.value.currentTime + 10, duration.value)
}

const skipBackward = () => {
  if (!videoRef.value) return
  videoRef.value.currentTime = Math.max(videoRef.value.currentTime - 10, 0)
}

const handleMouseMove = () => {
  showControls.value = true
  
  if (controlsTimeout) {
    clearTimeout(controlsTimeout)
  }
  
  controlsTimeout = setTimeout(() => {
    if (isPlaying.value) {
      showControls.value = false
    }
  }, 3000)
}

const initializeHls = (url: string) => {
  if (!videoRef.value) return
  
  console.log('🎬 Initializing video with URL:', url)
  
  // Check if it's an HLS stream
  if (url.includes('.m3u8') && Hls.isSupported()) {
    hls.value = new Hls({
      enableWorker: true,
      lowLatencyMode: false,
    })
    
    hls.value.loadSource(url)
    hls.value.attachMedia(videoRef.value)
    
    hls.value.on(Hls.Events.MANIFEST_PARSED, () => {
      console.log('✅ HLS manifest parsed')
    })
    
    hls.value.on(Hls.Events.ERROR, (event, data) => {
      console.error('HLS error:', data)
      if (data.fatal) {
        error.value = 'Video playback error. Please try again.'
      }
    })
  } else if (videoRef.value.canPlayType('application/vnd.apple.mpegurl')) {
    // Safari native HLS support
    videoRef.value.src = url
  } else {
    // Regular video file
    videoRef.value.src = url
  }
}

const fetchContent = async () => {
  const id = route.params.id as string
  if (!id) {
    error.value = 'Content ID not provided'
    loading.value = false
    return
  }
  
  loading.value = true
  error.value = ''
  
  try {
    // Get video details
    const video = await contentService.getVideoByUUID(id)
    content.value = video as any
    
    // Get stream URL
    const streamData = await contentService.getVideoStreamData(id)
    
    if (streamData.streamUrl && videoRef.value) {
      initializeHls(streamData.streamUrl)
    } else if ((video as any).video_url || (video as any).videoUrl) {
      initializeHls((video as any).video_url || (video as any).videoUrl)
    }
    
    // Fetch related content
    const browseData = await contentService.getBrowseContent(undefined, 10)
    relatedContent.value = (browseData.content || []).filter((item: any) => item.id !== id)
    
  } catch (err: any) {
    error.value = err.message || 'Failed to load content'
    console.error('Watch error:', err)
  } finally {
    loading.value = false
  }
}

const setupVideoListeners = () => {
  if (!videoRef.value) return
  
  videoRef.value.addEventListener('play', () => { 
    isPlaying.value = true 
    isBuffering.value = false
  })
  videoRef.value.addEventListener('pause', () => { isPlaying.value = false })
  videoRef.value.addEventListener('timeupdate', () => { 
    currentTime.value = videoRef.value?.currentTime || 0 
  })
  videoRef.value.addEventListener('loadedmetadata', () => { 
    duration.value = videoRef.value?.duration || 0 
  })
  videoRef.value.addEventListener('volumechange', () => { 
    isMuted.value = videoRef.value?.muted || false
    volume.value = videoRef.value?.volume || 0
  })
  videoRef.value.addEventListener('waiting', () => { isBuffering.value = true })
  videoRef.value.addEventListener('canplay', () => { isBuffering.value = false })
}

const handleKeyPress = (event: KeyboardEvent) => {
  switch (event.key) {
    case ' ':
    case 'k':
      event.preventDefault()
      togglePlay()
      break
    case 'f':
      toggleFullscreen()
      break
    case 'm':
      toggleMute()
      break
    case 'ArrowLeft':
      skipBackward()
      break
    case 'ArrowRight':
      skipForward()
      break
  }
}

onMounted(() => {
  fetchContent()
  setupVideoListeners()
  document.addEventListener('keydown', handleKeyPress)
  
  document.addEventListener('fullscreenchange', () => {
    isFullscreen.value = !!document.fullscreenElement
  })
})

onUnmounted(() => {
  if (hls.value) {
    hls.value.destroy()
  }
  if (controlsTimeout) {
    clearTimeout(controlsTimeout)
  }
  if (progressInterval) {
    clearInterval(progressInterval)
  }
  document.removeEventListener('keydown', handleKeyPress)
})
</script>

<template>
  <div class="min-h-screen bg-black text-white" ref="containerRef">
    <!-- Loading State -->
    <div v-if="loading" class="min-h-screen flex items-center justify-center">
      <Loader2 class="h-12 w-12 animate-spin text-purple-500" />
    </div>
    
    <!-- Error State -->
    <div v-else-if="error" class="min-h-screen flex flex-col items-center justify-center px-4">
      <p class="text-red-400 mb-4 text-center">{{ error }}</p>
      <div class="flex gap-4">
        <Button variant="outline" @click="router.back()">Go Back</Button>
        <Button @click="fetchContent">Try Again</Button>
      </div>
    </div>
    
    <!-- Video Player -->
    <div v-else-if="content" class="relative">
      <!-- Back Button -->
      <button
        @click="router.back()"
        class="fixed top-6 left-6 z-50 p-3 rounded-full bg-black/50 hover:bg-black/70 transition-colors backdrop-blur"
        :class="{ 'opacity-0': !showControls }"
      >
        <ArrowLeft class="h-5 w-5" />
      </button>
      
      <!-- Video Container -->
      <div 
        class="relative w-full h-screen cursor-pointer"
        @mousemove="handleMouseMove"
        @click="togglePlay"
      >
        <video
          ref="videoRef"
          class="w-full h-full object-contain bg-black"
          :poster="content.thumbnail_url"
          playsinline
        />
        
        <!-- Buffering Indicator -->
        <div v-if="isBuffering" class="absolute inset-0 flex items-center justify-center">
          <Loader2 class="h-16 w-16 animate-spin text-white" />
        </div>
        
        <!-- Center Play Button (when paused) -->
        <Transition name="fade">
          <div 
            v-if="!isPlaying && !isBuffering && showControls"
            class="absolute inset-0 flex items-center justify-center pointer-events-none"
          >
            <div class="w-24 h-24 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center">
              <Play class="h-12 w-12 text-white ml-2" />
            </div>
          </div>
        </Transition>
        
        <!-- Top Gradient -->
        <div 
          class="absolute top-0 left-0 right-0 h-32 bg-gradient-to-b from-black/80 to-transparent pointer-events-none transition-opacity"
          :class="showControls ? 'opacity-100' : 'opacity-0'"
        />
        
        <!-- Bottom Controls -->
        <Transition name="fade">
          <div 
            v-if="showControls"
            class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/90 via-black/60 to-transparent p-6"
            @click.stop
          >
            <!-- Progress Bar -->
            <div 
              class="relative h-1 bg-white/30 rounded-full mb-4 cursor-pointer group"
              @click="seek"
            >
              <div 
                class="absolute left-0 top-0 h-full bg-purple-500 rounded-full"
                :style="{ width: `${progress}%` }"
              />
              <div 
                class="absolute top-1/2 -translate-y-1/2 w-4 h-4 rounded-full bg-white opacity-0 group-hover:opacity-100 transition-opacity"
                :style="{ left: `calc(${progress}% - 8px)` }"
              />
            </div>
            
            <!-- Control Buttons -->
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-4">
                <!-- Play/Pause -->
                <button @click="togglePlay" class="hover:scale-110 transition-transform">
                  <Play v-if="!isPlaying" class="h-8 w-8" />
                  <Pause v-else class="h-8 w-8" />
                </button>
                
                <!-- Skip Back -->
                <button @click="skipBackward" class="hover:scale-110 transition-transform">
                  <SkipBack class="h-6 w-6" />
                </button>
                
                <!-- Skip Forward -->
                <button @click="skipForward" class="hover:scale-110 transition-transform">
                  <SkipForward class="h-6 w-6" />
                </button>
                
                <!-- Volume -->
                <button @click="toggleMute" class="hover:scale-110 transition-transform">
                  <VolumeX v-if="isMuted" class="h-6 w-6" />
                  <Volume2 v-else class="h-6 w-6" />
                </button>
                
                <!-- Time -->
                <span class="text-sm font-mono">
                  {{ formattedCurrentTime }} / {{ formattedDuration }}
                </span>
              </div>
              
              <!-- Title & Info -->
              <div class="hidden md:block flex-1 text-center px-8">
                <h1 class="text-lg font-semibold truncate">{{ content.title }}</h1>
                <p class="text-sm text-gray-400">{{ content.expert_name }}</p>
              </div>
              
              <div class="flex items-center gap-4">
                <!-- Episodes -->
                <button 
                  v-if="content.series_id"
                  @click="showEpisodes = true" 
                  class="hover:scale-110 transition-transform"
                >
                  <List class="h-6 w-6" />
                </button>
                
                <!-- Settings -->
                <button class="hover:scale-110 transition-transform">
                  <Settings class="h-6 w-6" />
                </button>
                
                <!-- Fullscreen -->
                <button @click="toggleFullscreen" class="hover:scale-110 transition-transform">
                  <Minimize v-if="isFullscreen" class="h-6 w-6" />
                  <Maximize v-else class="h-6 w-6" />
                </button>
              </div>
            </div>
          </div>
        </Transition>
      </div>
      
      <!-- Video Info (below player when not fullscreen) -->
      <div v-if="!isFullscreen" class="px-6 md:px-12 py-8 bg-[#0a0a0a]">
        <div class="max-w-4xl">
          <h1 class="text-2xl md:text-3xl font-bold mb-2">{{ content.title }}</h1>
          
          <div class="flex items-center gap-4 text-sm text-gray-400 mb-4">
            <span class="flex items-center gap-1">
              <User class="h-4 w-4" />
              {{ content.expert_name }}
            </span>
            <span class="flex items-center gap-1">
              <Clock class="h-4 w-4" />
              {{ formatTime(content.duration_seconds || 0) }}
            </span>
            <span class="px-2 py-0.5 rounded bg-gray-800">
              {{ content.category_name }}
            </span>
          </div>
          
          <p class="text-gray-300 leading-relaxed">
            {{ content.description }}
          </p>
        </div>
        
        <!-- Related Content -->
        <div v-if="relatedContent.length > 0" class="mt-12">
          <h2 class="text-xl font-semibold mb-4">More Like This</h2>
          <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
            <RouterLink 
              v-for="item in relatedContent.slice(0, 5)" 
              :key="item.id"
              :to="`/watch/${item.id}`"
              class="group"
            >
              <div class="aspect-video rounded-lg overflow-hidden bg-gray-800 mb-2">
                <img 
                  v-if="item.thumbnail_url"
                  :src="item.thumbnail_url"
                  :alt="item.title"
                  class="w-full h-full object-cover group-hover:scale-105 transition-transform"
                />
              </div>
              <h3 class="text-sm font-medium line-clamp-1 group-hover:text-purple-400 transition-colors">
                {{ item.title }}
              </h3>
            </RouterLink>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
